networks:
  app-net: null

services:
  debug_app:
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    #image: dctools/dev-container
    networks:
      - app-net
    volumes:
      - ../:/workspace
    post_start:
      - command: [sudo chown -R dctools /workspace]
